// api/keywords.js
export const keywords = {
    positiveKeywords: [
      { word: "cura", weight: 3 },
      { word: "descoberta", weight: 2 },
      { word: "ajudou", weight: 2 },
      { word: "vitória", weight: 3 },
      { word: "solidariedade", weight: 2 },
      { word: "avançou", weight: 2 },
      { word: "reconhecimento", weight: 2 },
      { word: "conquista", weight: 3 },
      { word: "inovação", weight: 2 },
      { word: "superação", weight: 2 },
      { word: "melhoria", weight: 2 },
      { word: "comunidade", weight: 1 },
      { word: "ajuda", weight: 1 },
      { word: "preservação", weight: 1 },
      { word: "vacinado", weight: 3 },
      { word: "campanha", weight: 1 },
      { word: "educação", weight: 2 },
      { word: "recuperação", weight: 2 },
      { word: "aliança", weight: 2 },
      { word: "progresso", weight: 2 },
      { word: "acolhimento", weight: 1 },
      { word: "inclusão", weight: 2 },
      { word: "emprego", weight: 2 },
      { word: "renovação", weight: 2 },
      { word: "acordo", weight: 2 },
      { word: "projeto social", weight: 3 },
      { word: "salvamento", weight: 3 },
      { word: "renascimento", weight: 3 },
      { word: "ajuda humanitária", weight: 2 },
      { word: "medicação", weight: 2 },
      { word: "apoio", weight: 2 },
      { word: "expansão", weight: 2 }
    ],
    negativeKeywords: [
      { word: "tragédia", weight: 3 },
      { word: "morte", weight: 3 },
      { word: "assassinato", weight: 3 },
      { word: "crime", weight: 2 },
      { word: "violência", weight: 2 },
      { word: "desastre", weight: 3 },
      { word: "incêndio", weight: 2 },
      { word: "fogo", weight: 2 },
      { word: "desabamento", weight: 2 },
      { word: "acidente", weight: 2 },
      { word: "explosão", weight: 2 },
      { word: "tragicamente", weight: 3 },
      { word: "colapso", weight: 2 },
      { word: "guerra", weight: 3 },
      { word: "conflito", weight: 3 },
      { word: "corrupção", weight: 2 },
      { word: "fraude", weight: 2 },
      { word: "crise", weight: 3 },
      { word: "falência", weight: 2 },
      { word: "dano", weight: 2 },
      { word: "assalto", weight: 2 },
      { word: "ferido", weight: 2 },
      { word: "infecção", weight: 3 },
      { word: "envenenamento", weight: 3 },
      { word: "atentado", weight: 3 },
      { word: "caos", weight: 3 },
      { word: "inundação", weight: 3 },
      { word: "desespero", weight: 3 },
      { word: "lockdown", weight: 2 },
      { word: "pandemia", weight: 3 },
      { word: "falta de", weight: 2 },
      { word: "explosivo", weight: 3 },
      { word: "repressão", weight: 3 },
      { word: "desabrigo", weight: 2 },
      { word: "enxurrada", weight: 2 },
      { word: "tragédias ambientais", weight: 3 }
    ],
    neutralKeywords: [
      { word: "notícia", weight: 1 },
      { word: "informação", weight: 1 },
      { word: "artigo", weight: 1 },
      { word: "análise", weight: 1 },
      { word: "relatório", weight: 1 }
    ]
  };
  